intel/bmap-tools

.travis.yml, bmaptools/BmapCopy.py, tests/helpers.py
XFS has feature about speculative pre-allocation of blocks based on
amount information written in the end of open file. In case of sparse
files it might lead to more mapped blocks than really expected.
Thus, truncate to desired size destination file as early as possible
and then write blocks that should be mapped the middle of it.
Closes #6
Signed-off-by: Alexander D. Kanevskiy <kad@kad.name>
=> XFS support: hint filesystem about expected maximum size of image file

bmaptools/BmapHelpers.py
Under some conditions, ioctl FIGETBSZ can't return real value.
We can try to use fallback via os.stat() to get block size.
Closes #15
Signed-off-by: Alexander D. Kanevskiy <kad@kad.name>
=> get_block_size: if we can't get from ioctl, try from os.stat()

bmaptools/TransRead.py, debian/control, packaging/bmap-tools.spec, tests/test_api_base.py
Some projects ship images compressed with zip, for cross OS
compatibility. Support read from such archives, assuming that
image is the first file in that archive. This is same assumption
as in case of tar.gz format.
Closes #10
Signed-off-by: Alexander D. Kanevskiy <kad@kad.name>
=> TransRead: support zip compressed images

bmaptools/TransRead.py
Commit 6343239fb was meant to take a different code path for urllib
downloads and local files, however the check to differentiate between
the two as broken as it turns out urllib objects also have fileno
attributes.
Fix this by specifically checking the object type and only then take the
direct codepath. This resolved bmaptool copy failing when using urls
instead of local files.
Signed-off-by: Sjoerd Simons <sjoerd.simons@collabora.co.uk>
=> TransRead: Fix differentiating between local files and urllib

bmaptools/CLI.py
When copying from a remote host, we first create a temporary copy
of the bmap and signature files locally. Unfortunately that does
not work in python3 and fails with this symptom:
$ python3 ./bmaptool -d copy https://xyz/image.raw ~/tmp/file
Traceback (most recent call last):
File "./bmaptool", line 11, in <module>
sys.exit(main())
File "/home/abityuts/git/bmap-tools/bmaptools/CLI.py", line 715, in main
args.func(args)
File "/home/abityuts/git/bmap-tools/bmaptools/CLI.py", line 477, in copy_command
writer.copy(False, not args.no_verify)
File "/home/abityuts/git/bmap-tools/bmaptools/BmapCopy.py", line 584, in copy
raise exc_info[1].with_traceback(exc_info[2])
File "/home/abityuts/git/bmap-tools/bmaptools/BmapCopy.py", line 503, in _get_data
self._f_image.seek(first * self.block_size)
File …
=> Fix copying bmap and signature files

bmaptools/TransRead.py
This patch fixes a regression introduced by commit 6343239fb2487c309c9573ee35e7832b08753180 -
reading a compressed file from an URL stopped working. Apparently urllib's file-like objects do have
a 'fileno', but reading from it gives EOF immediately. So lets use 'is_url' to make a decision about
whether we create a reader thread or not.
Change-Id: I6ba9570f823f3943f202d4b0170782a74aa0333e
Signed-off-by: Artem Bityutskiy <artem.bityutskiy@intel.com>
=> TransRead: unbreak reading compressed file from an URL

bmaptools/CLI.py
This fix avoids the following run-time exception:
$ bmaptool
Traceback (most recent call last):
File "/usr/bin/bmaptool", line 11, in <module>
load_entry_point('bmap-tools==3.4', 'console_scripts', 'bmaptool')()
File "/usr/lib/python3.6/site-packages/bmaptools/CLI.py", line 715, in main
args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
Suggested by: Simon McVittie [https://github.com/intel/bmap-tools/pull/51#issuecomment-398161212]
=> bmaptools/CLI.py: Print help in case of no arguments

packaging/bmap-tools.spec
* %__python is Prohibited, use %__python2 instead.
See: https://fedoraproject.org/wiki/Packaging:Python
* %__python is broken on fedora Rawhide.
* %__python2 macro is provides by python2-rpm-macros.
Signed-off-by: Ronan Le Martret <ronan.lemartret@iot.bzh>
=> Use python2 rpm macro for spec file

bmaptools/BmapCopy.py
New Linux Multi-Queue Block IO Queueing Mechanism does not have a noop
scheduler, which result in an error when trying to set the io scheduler.
Also according to the linux-blk maintainers:
"""
don't change the default io scheduler as none, which shouldn't
work well for slow disk, such as non-SSD.
"""
So, this patch basically does not bother the user if noop is not
available following this rationale :
If noop is not available is because the kernel is using multi queue
and then we should not change the io scheduler.
Fixes: #55
Signed-off-by: Ricardo Ribalda Delgado <ricardo.ribalda@gmail.com>
=> BmapCopy: Do not show a warning if noop io scheduder is not available

bmaptools/Filemap.py
In Python >= 3.7, if code in a generator raises StopIteration, it is
transformed into a RuntimeError instead of terminating the generator
gracefully.
Closes: https://github.com/intel/bmap-tools/issues/57  
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=915686
=> Filemap: catch StopIteration from next(iterator)

tests/test_api_base.py
When run on disorderfs (an artificial FUSE filesystem used by the
Reproducible Builds project to detect filesystem order dependencies),
we cannot map the file to detect holes. The same is likely to be true
for other simple FUSE filesystems.
=> test_api_base: Skip test if filesystem is unsuitable

bmaptools/CLI.py
Hello everyone, 
While using bmaptools with [debos](https://godoc.org/github.com/go-debos/debos), got an issue while copying the bmap file instead of the image file (by mistake). The error message was :
```
bmaptool: info: discovered bmap file 'in.bmap'
bmaptool: WARNING: image has the same path as the bmap file, dropping bmap
bmaptool: info: no bmap given, copy entire image to 'out'
bmaptool: info: 100% copied
bmaptool: info: synchronizing 'out'
bmaptool: info: copying time: 0.0s, copying speed 147.0 KiB/sec
```
It indicates that the entier image is copied. First, I did not realize my mistake and I thought that my image was correctly copied to my SD-card. In fact, it is copying the bmap file into the block device which is not what we want.
This commit will update it as an error instead …
=> bmaptool: CLI: Fail when copying a bmap file

tests/test_filemap.py
SyntaxWarning: "is" with a literal. Did you mean "=="?
if ranges_type is "mapped":
Signed-off-by: Artem Bityutskiy <artem.bityutskiy@intel.com>
=> tests: fix a couple of warnings

bmaptools/TransRead.py
If the TransRead read thread for some reason hits an exception (e.g. the
http connection got reset) the standard input from the decompressor
should still be closed otherwise bmaptool will just block without ever
detecting the read thread exploded.
Signed-off-by: Sjoerd Simons <sjoerd.simons@collabora.co.uk>
=> Always close the decompressor stdin

bmaptools/BmapHelpers.py, bmaptools/Filemap.py, docs/README, requirements-test.txt, tests/test_bmap_helpers.py
This is my first draft implementation. It has been tested on python 2.7 and 3.4.
All tests have been ran on a zfs file system (with and without fix applied) and an ext4 system.
=> zfs file system compatibility checks added. #67

bmaptools/BmapCopy.py, bmaptools/CLI.py
A conversation starter for https://github.com/intel/bmap-tools/issues/62 which currently works for me in achieving the bmap -> psplash interoperability. It is not as generic as it should as it depends on psplash named pipe interface.
=> bmaptool: Implement flag to interact with psplash progress

docs/man1/bmaptool.1
* Correct parameter name when documenting --psplash-pipe in the man page
* Expand documentation of --psplash-pipe to specify what is reported
cc @agherzan
=> Improve documentation of --psplash-pipe

bmaptools/BmapCopy.py
It would cause the following error while using —psplash-pipe:
```
sudo bmaptool copy xxx.xz /dev/sdb --psplash-pipe progress
Traceback (most recent call last):
File "/usr/local/bin/bmaptool", line 11, in <module>
load_entry_point('bmap-tools==3.6', 'console_scripts', 'bmaptool')()
File "/usr/local/lib/python3.8/dist-packages/bmap_tools-3.6-py3.8.egg/bmaptools/CLI.py", line 725, in main
File "/usr/local/lib/python3.8/dist-packages/bmap_tools-3.6-py3.8.egg/bmaptools/CLI.py", line 486, in copy_command
File "/usr/local/lib/python3.8/dist-packages/bmap_tools-3.6-py3.8.egg/bmaptools/BmapCopy.py", line 231, in set_psplash_pipe
NameError: name 'pipe' is not defined
```
=> Fix path parameter passing error of set_psplash_pipe function

bmaptools/TransRead.py, docs/man1/bmaptool.1
This adds basic functionality for copying files from the standard input, as proposed in #74. For example:
```sh
cat image.raw | bzip2 -d -c | sudo python bmaptool copy - /dev/sda --nobmap
```
It would be nice if `bmaptool` could handle the decompression of piped images as well, but this is not possible with the current file/compression type checks based on the file ending. I see two possible options two handle this:
1. Adding a `--file-type` or `--compression-type` flag to manually specify the type of archive/compression.
2. Integrate file type checks with file signatures using [python-magic](https://pypi.org/project/python-magic/), which strikes me as a better option. This would simplify the existing code for identifying the type of archive/compression and would also prevent …
=> Add basic copying from stdin

poetry.lock, pyproject.toml
This PR adds a [poetry](https://python-poetry.org/) manifest to the project to simplify further development, using modern Python dependency management.
=> Add `poetry` manifest for dependency management

bmaptools/TransRead.py
Adds support for getting the username and password from ~/.netrc if it's
not specified in the URL.
Signed-off-by: Joshua Watt <JPEWhacker@gmail.com>
=> Add .netrc support

bmaptools/TransRead.py
If the user doesn't have a .netrc file, bmaptool would fail. Fix this so that missing or incorrectly formatted .netrc files are not fatal
Signed-off-by: Joshua Watt <JPEWhacker@gmail.com>
=> Fix failures when .netrc is not present

bmaptools/BmapCopy.py, bmaptools/TransRead.py
These commits fix some warnings I came across when running bmaptool as a non-root user.
ssh is now told not to open any port forwardings even if configured in ssh_config.
The sysfs optimizations are updated to use the 'none' scheduler instead of noop (fixes #97 ), don't cause access warnings when the correct values are already set, and emit a suggestion for a udev rule otherwise.
=> Fix some unnecessary warnings, update i/o scheduler

pyproject.toml
This is only needed when running the build-time tests, and is not needed for ordinary use of the tool.
=> pyproject.toml: Move nose from dependencies to dev-dependencies
